### ISSUE TITLE
Why is there so much ai related code?

### ISSUE THREAD

**Issue by ghost** [escalab/SHMT#7]
There seems to be a few lines of code that look a lot like it has something to do with AI, is that necessary for what you want to achieve here?

**Comment by Kuan-ChiehHsu** [comment]
Hi, could you give a link for the particular line of code (or section) that you are referring to?

**Comment by ghost** [comment]
I don't exactly know, but I send the code to AI, to scan it and get more insight on how it works.
It identified it as a piece of code for AI training.
Might have been the kernel_model_training file name

**Comment by Kuan-ChiehHsu** [comment]
We do train some "AI models" as the edgeTPU kernels. Please refer to this paper: [NPU](https://ieeexplore.ieee.org/abstract/document/6493641) as we mentioned in our paper, thanks.
